# Create Deployment (APP deploy)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.app.name}}-deployment
  # Use the namespace we created in this chart
  namespace: {{ .Values.global.env}}-{{ .Values.global.app.name}}
  annotations:
    link.argocd.argoproj.io/external-link: https://{{ .Values.global.app.name}}.{{ .Values.global.env}}.{{.Values.global.app.domain}}
    {{- if .Values.global.datadog.enabled }}
    ad.datadoghq.com/{{ .Values.global.app.name}}-deployment.logs: >-
      [{
        "source": {{ .Values.global.datadog.app_type}},
        "service": "{{.Values.global.app.name}}-service",
      {{- if .Values.global.datadog.log_multiline_detection }}
        "auto_multi_line_detection": true,
        "pattern" : {{ .Values.global.datadog.log_multiline_pattern}}
      {{- end }}
      }]
  labels:
    tags.datadoghq.com/env: {{ .Values.global.env}}
    tags.datadoghq.com/service: {{ .Values.global.datadog.service }}
    tags.datadoghq.com/version: {{ .Values.global.datadog.agent_version}}
    {{- end }}
spec:
  {{- if not .Values.global.hpa.enabled }}
  # Replicas count
  replicas: {{ .Values.global.app.replicas}}
  {{- end }}
  selector:
    matchLabels:
      # Application name
      app: {{ .Values.global.app.name}}
  template:
    metadata:
      labels:
        app: {{ .Values.global.app.name}}
        app.kubernetes.io/name: {{ .Values.global.app.name}}
        {{- if .Values.global.datadog.enabled }}
        tags.datadoghq.com/env: {{ .Values.global.env}}
        tags.datadoghq.com/service: {{ .Values.global.app.name}}
        tags.datadoghq.com/version: {{ .Values.global.datadog.version }}
        admission.datadoghq.com/enabled: "true"
        annotations:
        admission.datadoghq.com/ruby-lib.version: {{ .Values.global.datadog.ruby_lib_version }}
        {{- end }}
    spec:
      containers:
        - name: container
          image: {{.Values.global.app.image.repository}}:{{.Values.global.app.image.tag}}
          command: {{.Values.global.app.command}}
          envFrom:
            # We get Env variables in the pod from the secret we created
            - secretRef:
                # We refer to the name of the secret
                name: {{ .Values.global.app.name}}-secret
          env:
          {{- range $key, $value := .Values.global.app.variables.list }}
            - name: {{ $key }}
              value: {{ $value }}
          {{- end }}
