apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.app.name}}-secret
  namespace: {{ .Values.env}}-{{ .Values.app.name}}
spec:
  secretStoreRef:
    name: {{ .Values.app.name}}-secrets
    kind: SecretStore
  data:
    # metadataPolicy to fetch all the tags in JSON format
    {{ range .Values.secrets.list }}
    - secretKey: {{ . }}
      remoteRef:
        metadataPolicy: Fetch
        key: "/{{ $.Values.env}}/{{ $.Values.secrets.app}}/{{ . }}"
    {{ end }}
