{{- if and .Values.global.ingress.enabled .Values.global.ingress.create_certificate}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns-nginx-issuer
spec:
  acme:
    privateKeySecretRef:
      name: letsencrypt
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          route53:
            region: {{.Values.global.app.region  | default "us-east-1"}}
{{- end }}
