{{- if .Values.istio.enabled }}
# Istio-system gateway creation
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.app.name}}-gateway
  namespace: {{.Values.env }}-{{ .Values.app.name}}
spec:
  selector:
    # Use istio default ingress gateway
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - {{ .Values.app.name}}.{{ .Values.env}}.{{.Values.istio.domain}}
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        # This should match the Certificate secretName
        credentialName: {{ .Values.app.name}}-tls
      hosts:
        - {{ .Values.app.name}}.{{ .Values.env}}.{{.Values.istio.domain}}
{{- end }}
