apiVersion: v1
kind: Service
metadata:
  name: {{.Values.global.app.name}}-service
  namespace: {{ .Values.global.env}}-{{ .Values.global.app.name}}
spec:
  ports:
    - name: http
      targetPort: {{.Values.global.service.targetPort | default "3000"}}
      port: {{.Values.global.service.port | default "3000"}}
  selector:
    # This is app name label
    app: {{.Values.global.app.name }}
