# Environment to deploy app to.
global:
  env: local

# Disable or enable Istio or Ingress-Nginx.Only one could be enabled. Other one should be disabled.

## Istio settings:
  istio:
    enabled: false
    create_certificate: false
    # Use tls_certificate_name if cluster have already created certificates
    tls_certificate_name: ""
    domain: domain.local
    port: 3000

## Ingress-Nginx settings:
  ingress:
    enabled: false
    create_certificate: false
    # Use tls_certificate_name if cluster have already created certificates
    tls_certificate_name: ""
    domain: domain.local
    port: 3000

## Application deploy settings:
  app:
    name: app
    region: aws-region
    containerName: ""
    domain: domain.local

## Number of pod replicas:
    replicas: 1

## Command to run in pod container:
    command: ''

## Set image repository:
    image:
      repository: <aws-account-id>.dkr.ecr.<aws-region>.amazonaws.com/<app-name>
      # https://github.com/aws-actions/configure-aws-credentials/blob/main/action.yml#L71  We should use this in the future

## Set image tag. `Dev-latest` by default.
      tag: dev-latest

## Specify a imagePullPolicy
## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'.
      imagePullPolicy: Always

## Define a list of variables. Use it like <variable-name>:<value>:
    variables:
      list:
        APP_NAME: ""

## Define a list of secrets. Secrets should be pulled to the Parameter store with the path: /env/<app-name>/<secret-name>:
  secrets:
    app: ""
    list:
      - ""

## Set a port app uses:
  service:
    port: 3000
    targetPort: 3000

## Set a TLS certificate issuer:
  gateway:
    tlsIssuer: ""

## Define a list of pre-created IAM roles (by Terraform EKS module for example):
  iam_roles:
    r53: ""
    ssm: ""
